version: '3.8'

services:
  # Backend service
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=bank
      - DB_PORT=3306
    depends_on:
      - mysql

  # Frontend service
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # MySQL service
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bank
      MYSQL_ROOT_PASSWORD: "" #igen lösenord

    volumes:
      - mysql_data:/var/lib/mysql

# Volumes för att lagra MySQL-data
volumes:
  mysql_data:
