name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:

  test:
    name: Test with RTL
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: List frontend directory
        working-directory: ./frontend
        run: ls l
          shell: bash

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install --prefix ./frontend

      - name: Run Tests
        working-directory: ./frontend
        run: npm run test
        env:
          test: true

  deployment:
    needs: test
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: check out Repo
        uses: actions/checkout@v4

      - name: Copy file to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "."
          target: "/home/ubuntu/chasacademy-banksite-2024"

      - name: Run Docker on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/chasacademy-banksite-2024
            sudo docker-compose down
            sudo docker-compose up --build -d   